admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
      
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9191
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: tcp_backend

  clusters:
  - name: tcp_backend
    connect_timeout: 10s
    circuit_breakers:
      thresholds:
      - max_connections: 4294967295
        max_pending_requests: 4294967295
        max_requests: 4294967295
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: tcp_backend
      endpoints:
      - lb_endpoints: